version: 2.1

commands:
  restore-sbt-cache:
    description: "Restore sbt cache"
    steps:
      - restore_cache:
          key: v1-sbt-cache-{{ checksum "backend/build.sbt" }}

  save-sbt-cache:
    description: "Save sbt cache"
    steps:
      - save_cache:
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
          key: v1-sbt-cache-{{ checksum "backend/build.sbt" }}

  restore-npm-cache:
    description: "Restore npm cache"
    steps:
      - restore_cache:
          key: v1-npm-cache-{{ checksum "frontend/package-lock.json" }}

  save-npm-cache:
    description: "Save npm cache"
    steps:
      - save_cache:
          paths:
            - "frontend/node_modules"
          key: v1-npm-cache-{{ checksum "frontend/package-lock.json" }}

jobs:
  scapegoat:
    working_directory: ~/repo
    docker:
      - image: mozilla/sbt:latest
    steps:
      - checkout
      - restore-sbt-cache
      - run:
          name: Run scapegoat
          command: |
            cd backend
            sbt scapegoat
      - save-sbt-cache
      - store_artifacts:
          path: ~/repo/backend/target/scala-2.12/scapegoat-report/scapegoat.html

  unit_test_backend:
    working_directory: ~/repo
    docker:
      - image: mozilla/sbt:latest
    steps:
      - checkout
      - restore-sbt-cache
      - run:
          name: Run unit tests
          command: |
            cd backend
            sbt test
      - save-sbt-cache
      - store_test_results:
          path: ~/repo/backend/target/test-reports

  lint:
    working_directory: ~/repo
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - restore-npm-cache
      - run:
          name: Run linter
          command: |
            cd frontend
            npm install
            npm run lint
      - save-npm-cache
      - store_test_results:
          path: ~/repo/backend/target/test-reports

  unit_test_frontend:
    working_directory: ~/repo
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - restore-npm-cache
      - run:
          name: install deps
          command: |
            cd frontend
            npm install
      - save-npm-cache
      - run:
          name: install deps
          command: |
            cd frontend
            npm install
            npm test
      - store_test_results:
          path: ~/repo/backend/target/test-reports

workflows:
  pipeline:
    jobs:
      - lint
      - unit_test_frontend
      - scapegoat
      - unit_test_backend
