version: 2.1

commands:
  restore-sbt-cache:
    description: "Restore sbt cache"
    steps:
      - restore_cache:
          key: v1-sbt-cache-{{ checksum "backend/build.sbt" }}

  save-sbt-cache:
    description: "Save sbt cache"
    steps:
      - save_cache:
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
          key: v1-sbt-cache-{{ checksum "backend/build.sbt" }}

jobs:
  scapegoat:
    working_directory: ~/repo
    docker:
      - image: mozilla/sbt:latest
    steps:
      - checkout
      - restore-sbt-cache
      - run:
          name: Run scapegoat
          command: |
            cd backend
            sbt scapegoat
      - save-sbt-cache

workflows:
  backend:
    jobs:
      - scapegoat
